### ISSUE TITLE
关于step size的问题

### ISSUE THREAD

**Issue by rainofbow** [zengh5/TA_feature_FT#1]
您好，论文中说step size是2，但是您代码中这里的step size为什么是 self.alpha = self.epsilon / 16.？

**Comment by zengh5** [comment]
谢谢你提出的问题。
1 论文中的学习率2指的是baseline attack用到的学习率. 这个其实从我的代码中是看不到的。
2. self.alpha1 是fine-tune 阶段用的学习率，在最大budget是linf = 16情况下, 此时微调阶段学习率为16/16=1. 非常抱歉，我在论文中没有说明此参数的设置。
抱歉对你带来了困扰。事实上self.alpha1=2， N_fk=5, 和 self.alpha1=1， N_fk=10 结果非常类似。


------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Oct 30, 2024 04:54 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[zengh5/TA_feature_FT] 关于学习率的问题 (Issue #1)

&nbsp;



 
您好，论文中说学习率是2，但是您代码中这里的学习率为什么是 self.alpha1 = self.epsilon / 16.？

**Comment by rainofbow** [comment]
> =
谢谢您的解答
